config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :admin do
    resources :equibs do
      collection do
        get :dashboard
      end
    end
  end

  resources :equibs do
    resources :repairs
  end

  resources :welcomes do
    get 'meter'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equib.rb
class Equib < ApplicationRecord

 mount_uploader :image, ImageUploader

  has_many :repairs

  def self.total_price
  sum = 0
  @equibs = Equib.all
  @equibs.each do |equib|
    if equib.price.present?
      sum = sum + equib.price
    end
  end
  sum
end


def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |equib|
      csv << equib.attributes.values_at(*column_names)
    end
  end
end
end

app/models/repair.rb
class Repair < ApplicationRecord

  belongs_to :equib

  def self.total_fees
    sum = 0
    @repair.fees.each do |fees|
      if @equib.fees.present?
        sum += self.fees
      end
    end
    sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def admin?
    is_admin
  end
end

app/controllers/admin/equibs_controller.rb
class Admin::EquibsController < ApplicationController
  # before_action :authenticate_user!
  # before_action :admin_required
  layout "admin"
  def new
    @equib = Equib.new
  end

  def create
    @equib = Equib.new(equib_params)
    if @equib.save
      redirect_to admin_equibs_path,notice: "已新增！"
    else
      render :back
    end
  end

  def index
    @equibs = Equib.all
    flash[:notice] = "测试版，所有权限暂时开放！"
    respond_to do |format|
      format.html
      format.csv { send_data @equibs.to_csv }
      format.xls  { send_data @equibs.to_csv(col_sep: "\t") }
    end
  end

  def edit
    @equib = Equib.find(params[:id])
  end

  def update
    @equib = Equib.find(params[:id])
    if @equib.update(equib_params)
      redirect_to admin_equibs_path, notice: "更新成功！"
    else
      render :edit
    end
  end

  def show
    @equib = Equib.find(params[:id])
    @repairs = @equib.repairs

    @qr = RQRCode::QRCode.new(equib_url(@equib).to_s, :size => 5, :level => :h )
  end

  def destroy
    @equib = Equib.find(params[:id])
    @equib.destroy
    redirect_to admin_equibs_path, alert: "已删除！"
  end


  private

  def equib_params
    params.require(:equib).permit(:title, :department, :position, :principal, :purchase_date, :is_for_production, :use_state, :origin, :model, :supplier, :warranty, :description, :price, :age_limit, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def admin_required
    if !current_user.admin?
      redirect_to '/', alert: "你不是管理员～"
    end 
  end


end

app/controllers/equibs_controller.rb
class EquibsController < ApplicationController
  # before_action :authenticate_user!, only: [:index]
  def show
  @equib = Equib.find(params[:id])
  @repairs = @equib.repairs

    @qr = RQRCode::QRCode.new(equib_url(@equib).to_s, :size => 5, :level => :h )
end

def index
  @equibs = Equib.order("id DESC")
  flash[:notice] = "测试版，所有权限暂时开放！"
end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController

  def new
    @equib = Equib.find(params[:equib_id])
    @repair = Repair.new
  end

  def create
    @equib = Equib.find(params[:equib_id])
    @repair = Repair.new(repair_params)
    @repair.equib = @equib
    if @repair.save
      redirect_to equib_path(@equib), notice: "已添加！"
    else
      render :new,notice: "失败！"
    end
  end
  def edit
    @repair = Repair.find(params[:id])
  end

  def update
    @repair = Repair.find(params[:id])
    if @repair.update(repair_params)
      redirect_to admin_equib_path(@repair.equib),notice: "已修改！"
    else
      render :edit
    end
  end

  private

  def repair_params
    params.require(:repair).permit(:cause, :fees, :is_wireman, :method)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  def index
  end
end

app/helpers/admin/equibs_helper.rb
module Admin::EquibsHelper
  def render_total_price
  Equib.total_price
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
  :user
end

def resource
    @resource ||= User.new
end

def resource_class
    User
end

def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
end
end

app/helpers/equibs_helper.rb
module EquibsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/repairs_helper.rb
module RepairsHelper

  def render_total_fees(equib)
    sum = 0
    equib.repairs.each do |repair|

      if repair.fees.present?
        sum += repair.fees
      end
    end
    sum
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/equibs/dashboard.html.erb
<div class="container">
    <h1 class="text-center">此页面待开发。。。</h1>
</div>

<%= link_to("返回",admin_equibs_path,class: "btn btn-danger",style:"width:100%")%>

app/views/admin/equibs/edit.html.erb
<h1 class="text-center">修改设备信息</h1>
<div class="container form-group-bc">


  <%= simple_form_for [:admin,@equib] do |f| %>
  <div class="col-md-3 col-xs-6"><div class="form_title"><%= f.input :title,label:"名称"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_department"><%= f.input :department,label:"所属部门"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_position"><%= f.input :position,label:"存放位置"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_principal"><%= f.input :principal,label:"负责人"%></div></div>


  <div class="col-md-3 col-xs-6"><div class="form_use_state"><%= f.input :use_state,label:"使用状态"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_origin"><%= f.input :origin,label:"产地"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_model"><%= f.input :model,label:"型号"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_supplier"><%= f.input :supplier,label:"供应商"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_warranty"><%= f.input :warranty,label:"保修期"%></div></div>

  <div class="col-md-3 col-xs-6"><div class="form_price"><%= f.input :price,label:"价格"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_age_limit"><%= f.input :age_limit,label:"年限"%></div></div>
  <div class="col-md-12"><div class="form_description"><%= f.input :description,label:"描述"%></div></div>
  <div class="col-md-12"><div class="form_purchase_date"><%= f.input :purchase_date,label:"购入日期"%></div></div>
  <div class="col-md-12"><div class="form_is_for_production"><%= f.input :is_for_production,label:"是否为生产设备"%></div></div>
  <div class="col-md-12"><div class="form_image"><%= f.input :image, as: :file, class: "btn btn-default"%></div></div>

  <div class="col-md-12"><%= f.submit '提交',data: {disable_with: "Submiting..."}, class: "btn btn-primary btn-lg"%></div>
  <% end %>

</div>

app/views/admin/equibs/index.html.erb
<div class="container">
  <h2 class="text-center">机器列表</h2>

  <div class="haha">
    <%= link_to("新增设备",new_admin_equib_path, class:"btn btn-success")%>
  </div>


  <div class="haha" style="overflow-x: auto;">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>图片</th>
                <th>机器名称</th>
                <th>所属部门</th>
                <th>存放位置</th>
                <th>操作选项</th>
            </tr>
        </thead>
        <tbody>
            <% @equibs.each do |equib| %>
            <tr>
                <td><%= equib.id %></td>
                <td>
                    <%= link_to admin_equib_path(equib) do %>
                    <% if equib.image.present? %>
                    <%= image_tag(equib.image.thumb.url, class: "thumbnail haha3")%>
                <% else%>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail haha3")%>
                    <% end %>
                    <% end %>
                </td>
                <td><%= link_to(equib.title,admin_equib_path(equib))%></td>
                <td><%= equib.department %></td>
                <td><%= equib.position %></td>
                <td><%= link_to("修改属性", edit_admin_equib_path(equib),class: "btn btn-info btn-md")%>
                    <%= link_to("删除这个设备", admin_equib_path(equib),method: :delete, data: {confirm:"你确定要删除这个设备吗？删除后无法找回！"},class: "btn btn-danger btn-md")%>
                </tmd
            </tr>
            <% end %>
        </tbody>
    </table>
  </div>
  <div class="group total pull-right col-xs-12">
     <span style="font-size: 20px;">资产总额：</span>
      <span class="label label-success" style="font-size:150%">
          <%= render_total_price %>
          CNY
      </span>
  </div>
  <br/>
  <hr/>
  <div class="button">
      <span style="font-size:20px;">导出Excel</span>
      <%= link_to("CSV", admin_equibs_path(format: "csv"), class: "btn btn-success") %>
      |
      <%= link_to("Excel", admin_equibs_path(format: "csv") ,class: "btn btn-success")%>
  </div>

</div>

app/views/admin/equibs/index.xls.erb
<?xml version="1.0"?>
<Workbook
    xmlns="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:x="urn:schemas-microsoft-com:office:excel"
    xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell>
                    <Data ss:Type="String">ID</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">设备名称</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">所属部门</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">存在位置</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">负责人</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">购买日期</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">是否生产设备</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">状态</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">产地</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">型号</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">供应商</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">保修期</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">备注</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">单价</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">年限</Data>
                </Cell>
                <Cell>
                    <Data ss:Type="String">图片</Data>
                </Cell>

            </Row>
            <% @equibs.each do |equib| %>
            <Row>
                <Cell>
                    <Data ss:Type="Number"><%= equib.id %></Data>
                </Cell>
                <Data ss:Type="String"><%= equib.title %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.department %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.position %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.principal %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.purchase_date %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.is_for_production %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.use_state %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.origin %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.model %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.supplier %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.warranty %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.description %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.price %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.age_limit %></Data>
            </Cell>
            <Cell>
                <Data ss:Type="String"><%= equib.image %></Data>
            </Cell>

        </Row>
        <% end %>
    </Table>
</Worksheet>
</Workbook>

app/views/admin/equibs/new.html.erb
<div class="container form-group-bc">
  <h1 class="text-center">新增设备</h1>

  <%= simple_form_for [:admin,@equib] do |f| %>
  <div class="col-md-3 col-xs-6"><div class="form_title"><%= f.input :title,label:"名称"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_department"><%= f.input :department,label:"所属部门"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_position"><%= f.input :position,label:"存放位置"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_principal"><%= f.input :principal,label:"负责人"%></div></div>


  <div class="col-md-3 col-xs-6"><div class="form_use_state"><%= f.input :use_state,label:"使用状态"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_origin"><%= f.input :origin,label:"产地"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_model"><%= f.input :model,label:"型号"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_supplier"><%= f.input :supplier,label:"供应商"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_warranty"><%= f.input :warranty,label:"保修期"%></div></div>

  <div class="col-md-3 col-xs-6"><div class="form_price"><%= f.input :price,label:"价格"%></div></div>
  <div class="col-md-3 col-xs-6"><div class="form_age_limit"><%= f.input :age_limit,label:"年限"%></div></div>
  <div class="col-md-12"><div class="form_description"><%= f.input :description,label:"描述"%></div></div>
  <div class="col-md-12"><div class="form_purchase_date"><%= f.input :purchase_date,label:"购入日期"%></div></div>
  <div class="col-md-12"><div class="form_is_for_production"><%= f.input :is_for_production,label:"是否为生产设备"%></div></div>
  <div class="col-md-12"><div class="form_image"><%= f.input :image, as: :file, class: "btn btn-default"%></div></div>

  <div class="col-md-12"><%= f.submit '提交',data: {disable_with: "Submiting..."}, class: "btn btn-primary btn-lg"%></div>
  <% end %>

</div>

app/views/admin/equibs/show.html.erb
<div class="container">
  <h1 class="text-center">设备信息<small><%= @equib.title %>(<%= @equib.department %>)</small>
  </h1>
  <br/><br/><hr/>

  <div class="row">
      <div class="col-xs-12 col-md-6">
          <% if @equib.image.present? %>
          <%= image_tag(@equib.image.medium.url, class: "thumbnail img-responsive hihi")%>
      <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail img-responsive hihi")%>
          <% end %>
      </div>
      <div class="col-xs-12 col-md-6">
          <div class="well" >
            <h5>机器名称：<%= @equib.title%></h5>
            <h5>机器备注：<%= @equib.description%></h5>
            <h5>所属部门：<%= @equib.department%></h5>
            <h5>存放位置：<%= @equib.position%></h5>
            <h5>机器型号：<%= @equib.model%></h5>
            <h5>负责人：<%= @equib.principal%></h5>
            <h5>供应商：<%= @equib.supplier%></h5>
            <h5>保修期：<%= @equib.warranty%></h5>
            <h5>产地：<%= @equib.origin%></h5>
            <h5>购入日期：<%= @equib.purchase_date%></h5>
            <h5>是否为生产设备：<%= @equib.is_for_production%></h5>
            <h5>价格：<%= @equib.price%></h5>
            <h5>年限<%= @equib.age_limit%></h5>
            <h5>使用状态：<%= @equib.use_state%></h5>

              <hr/>
            <%= link_to("修改属性", edit_admin_equib_path(@equib),class: "btn btn-primary")%>
              <br/>

          </div>
      </div>
  </div>

  <h2 class="text-center">维修记录</h2>

  <%= link_to("添加维修记录",new_equib_repair_path(@equib), class: "btn btn-danger pull-db")%>
  <hr/>

  <p class="pull-right">
      累计维修金额
      <span class="label label-danger" style="font-size:150%">
          ¥<%= render_total_fees(@equib)%></span>
  </p>
  <% @repairs.each do |repair| %>
  <div class="col-xs-12 well">
      <p>故障原因：<%= repair.cause %></p>
      <p>维修项目：<%= repair.method %></p>
      <h5>维修费用：<%= repair.fees %>
          <% if repair.is_wireman? %>
          <span class="label label-success label-sm">内部维修</span>
      <% else %>
          <span class="label label-danger label-sm">外部维修</span>
          <% end %>
      </h5>
      <p><%= repair.created_at.to_s(:db)%></p>

  </div>
  <% end %>
  <br/>
  <h3 class="text-center">机器二维码标签</h3><hr/>
  <div class="rqrcode panel" >
      <%= raw @qr.as_html %>
  </div>

</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container-fluid bg-4" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Equibhub
        <br/>Design by activeliang
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" >
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a href="/" class="navbar-brand">Diastar&Errepi Equibhub</a>
        </div>

        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav navbar-right">

                <% if !current_user %>
                <!-- <li><%= link_to("注册", new_user_registration_path)%></li> -->
                <!-- <li><%= link_to(content_tag(:i, '登入',class: "fa fa-sign-in"), new_user_session_path)%></li> -->
                <li>
                    <a href="#" data-toggle="modal" data-target="#signup-modal">注册</a>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#login-modal">
                        <i class="fa fa-sign-in"></i>登入
                    </a>
                </li>
            <% else %>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!
                        <%= current_user.email %>
                        <b class="caret"></b>
                        <ul class="dropdown-menu">
                            <li><%= link_to("管理员后台", admin_equibs_path)%></li>
                            <li class="divider"></li>
                            <li><%= link_to(content_tag(:i,'登出',class: "fa fa-sign-out"), destroy_user_session_path, method: :delete)%></li>
                        </ul>
                    </a>
                </li>
                <% end %>
            </ul>

        </div>
    </div>
</nav>

<!-- 以下代码添加在最后 -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
        <div class="loginmodal-container">
            <h2>Log in</h2>
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-inputs">
                <%= f.input :email, required: false, autofocus: true %>
                <%= f.input :password, required: false %>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, "Log in" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="loginmodal-container">
            <h2>Sign up</h2>
            <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :email, required: true, autofocus: true %>
                <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                <%= f.input :password_confirmation, required: true %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, "Sign up" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/equibs/show.html.erb
<div class="container">
  <h1 class="text-center">设备信息<small><%= @equib.title %>(<%= @equib.department %>)</small>
  </h1>
  <br/><br/><hr/>

  <div class="row">
      <div class="col-xs-6 col-xs-12">
          <% if @equib.image.present? %>
          <%= image_tag(@equib.image.medium.url, class: "thumbnail img-responsive hihi")%>
      <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail img-responsive hihi")%>
          <% end %>
      </div>
      <div class="col-xs-6 col-xs-12">
          <div class="well">
            <h5>机器名称：<%= @equib.title%></h5>
            <h5>机器备注：<%= @equib.description%></h5>
            <h5>所属部门：<%= @equib.department%></h5>
            <h5>存放位置：<%= @equib.position%></h5>
            <h5>机器型号：<%= @equib.model%></h5>
            <h5>负责人：<%= @equib.principal%></h5>
            <h5>供应商：<%= @equib.supplier%></h5>
            <h5>保修期：<%= @equib.warranty%></h5>
            <h5>产地：<%= @equib.origin%></h5>
            <h5>购入日期：<%= @equib.purchase_date%></h5>
            <h5>是否为生产设备：<%= @equib.is_for_production%></h5>
            <h5>价格：<%= @equib.price%></h5>
            <h5>年限<%= @equib.age_limit%></h5>
            <h5>使用状态：<%= @equib.use_state%></h5>
              <hr/>
              <%= link_to("纠错", '#',class: "btn btn-info btn-md ")%>
              <br/>
              <hr/>
          </div>
      </div>
  </div>

  <h2 class="text-center">维修记录</h2>
  <%= link_to("添加维修记录",new_equib_repair_path(@equib), class: "btn btn-danger pull-db")%>
  <hr/>
  <p class="pull-right">
      累计维修金额
      <span class="label label-danger" style="font-size:150%">
          ¥<%= render_total_fees(@equib)%></span>
  </p>
  <% @repairs.each do |repair| %>
  <div class="col-xs-12 well">
      <p>故障原因：<%= repair.cause %></p>
      <p>维修项目：<%= repair.method %></p>
      <h5>维修费用：<%= repair.fees %>
          <% if repair.is_wireman? %>
          <span class="label label-success label-sm">内部维修</span>
      <% else %>
          <span class="label label-danger label-sm">外部维修</span>
          <% end %>
      </h5>
      <p><%= repair.created_at.to_s(:db)%></p>

  </div>
  <% end %>
  <br/>
  <h3 class="text-center">机器二维码标签</h3><hr/>
  <div class="rqrcode panel" >
      <%= raw @qr.as_html %>
  </div>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Diastar&Errepi Equibhub</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes"%>
            <div class="row">
                <div class="col-md-2 ">
                    <ul class="nav nav-pills nav-stacked clearfix" style="max-width: 300px;">
                        <li >
                            <%= link_to("所有设备", admin_equibs_path, class: "btn btn-primary") %>
                        </li>
                        <li>
                            <%= link_to("后台数据", dashboard_admin_equibs_path, class: "btn btn-success")%></li>
                    </ul>
                </div>
                <div class="col-md-10 clearfix">
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= render "common/footer"%>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Diastar&Errepi Equibhub</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
              <%= render "common/navbar"%>
            </div>
            <%= render "common/flashes"%>
            <%= yield %>
        </div>
        <%= render "common/footer"%>
    </body>
</html>

app/views/repairs/new.html.erb
<div class="container form-group-bc">
    <h2 class="text-center">添加维修记录<small><%= @equib.title %>
            >
            <%= @equib.position %></small>
    </h2>

    <%= simple_form_for [@equib, @repair] do |f| %>
    <div class="group"><%= f.input :cause, label: "故障原因"%></div>
    <div class="group"><%= f.input :method, label: "维修项目"%></div>
    <div class="group"><%= f.input :fees, label: "费用"%></div>
    <div class="group"><%= f.input :is_wireman, label: "是否内部电工维修"%></div>
    <%= f.submit '提交', data: {disable_with: "提交中...."}, class: "btn btn-primary btn-lg"%>
    <% end %>

</div>

app/views/welcome/index.html.erb
<head>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="title">
  <h3>PLASM.it - 2017</h3>
  <h1 style="font-size: 40px;">Diastar&Errepi Equibhub</h1>
  <h2>亚瑱嘉品固定资产管理</h2>
</div>
<div class="more-pens">
  <%= link_to("马上进入", equibs_path, class: "btn btn-danger  white-mode")%>
</div>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.4.2/pixi.min.js'></script>

  <script src="index.js"></script>


</body>